extends Resource

enum Location { LEFT, MIDDLE, RIGHT, ANY }
enum Row { FRONT, BACK, BOTH }
enum Side { ALLY, ENEMY, BOTH }
enum Stat { POWER, HEALTH, BOTH }
enum TargetType { ALL, HIGHEST_POWER, LOWEST_POWER, HIGHEST_HEALTH, LOWEST_HEALTH, ABOVE_POWER_THRESHOLD, BELOW_POWER_THRESHOLD, ABOVE_HEALTH_THRESHOLD, BELOW_HEALTH_THRESHOLD }
